"""use symmetric encryption for api keys

Revision ID: 1d7905b05e0d
Revises: e57d8b54be2e
Create Date: 2026-09-23 17:03:17.994543
"""
from alembic import op
import sqlalchemy as sa

revision = '1d7905b05e0d'
down_revision = 'e57d8b54be2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_secret_encrypted', sa.String(length=255), nullable=False))
    op.drop_column('api_keys', 'key_secret_hash')
    op.drop_index('ix_payments_id', table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.add_column('api_keys', sa.Column('key_secret_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('api_keys', 'key_secret_encrypted')
    # ### end Alembic commands ###
