"""create_refunds_table

Revision ID: 39e6e7f3a6f6
Revises: 1d7905b05e0d
Create Date: 2026-09-24 14:49:42.245597
"""

from alembic import op
import sqlalchemy as sa

revision = "39e6e7f3a6f6"
down_revision = "1d7905b05e0d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refunds",
        sa.Column("refund_id", sa.String(length=50), nullable=False),
        sa.Column("payment_id", sa.String(length=50), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.payment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refunds_merchant_id"),
        "refunds",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refunds_payment_id"), "refunds", ["payment_id"], unique=False
    )
    op.create_index(
        op.f("ix_refunds_refund_id"), "refunds", ["refund_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_refund_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_payment_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_merchant_id"), table_name="refunds")
    op.drop_table("refunds")
    # ### end Alembic commands ###
