"""add reference_id to ledger_transactions

Revision ID: 3ec5ae947706
Revises: 396909aeeb78
Create Date: 2026-09-24 10:19:22.155934
"""
from alembic import op
import sqlalchemy as sa

revision = '3ec5ae947706'
down_revision = '396909aeeb78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_transactions', sa.Column('reference_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_column('ledger_transactions', 'reference_id')
    # ### end Alembic commands ###
