"""create orders table

Revision ID: fe3685c0dc97
Revises: b2c3d4e5f6a7
Create Date: 2026-09-22 17:45:28.961515
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "fe3685c0dc97"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("receipt", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_merchant_id"), "orders", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_orders_order_id"), "orders", ["order_id"], unique=True
    )
    op.drop_constraint("api_keys_key_id_key", "api_keys", type_="unique")
    op.drop_constraint("users_email_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.create_unique_constraint("api_keys_key_id_key", "api_keys", ["key_id"])
    op.drop_index(op.f("ix_orders_order_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
